### ISSUE TITLE
[Thread] Open-Sourcing SkyShift

### ISSUE THREAD

**Issue by michaelzhiluo** [sky-shift/skyshift#289]
These are the following steps to open-source SkyShift:

- [ ] Docs
    - [x] Docs for Services @pr2satish @colinc9 @ArnavBalyan (#312, In PR)
    - [ ] Polish/Readjust the Docs; Typos, Potential Reorganization of Different Pages (Everyone)
    - [x] Docs for the Cloud Feature @just-in-chang (#307)
    - [x] Fixing Slurm Documentation @dmatch01 @dc-base  (#317, In PR)
    - [x] Ray Documentation @AlexCuadron (In PR, #313)
    - [x] Docs on Scheduler and Scheduling Plugins @dmatch01 (#299)
    - [x] Automatic Documentation for our Python API and CLI. @ArnavBalyan  (#298)
    - [x] Release Notes @michaelzhiluo

- [x] Features
    - [x] Ray Test PR @AlexCuadron (In PR, #230) 

- [x] Clean up README.md  @michaelzhiluo (Done!)
- [x] Github actions for website.

- [x] Create roadmap.md @MEllis-github @dmatch01 (#296 , #315 )
- [x] Close issues or mark as stale

- [x] Create SkyShift examples for AI serving, AI training, and different workloads. @AlexCuadron @praveingk @michaelzhiluo @colinc9 (Every PR will need documentation under examples/)
     - [x] Multiple vLLMs across clusters @praveingk  @michaelzhiluo (#319, In PR)
     - [x] Simple Spark Application @ArnavBalyan (#300)
     - [x] SparkSQL with TPCDS/TPCH @ArnavBalyan (#316, In PR)
     - [x] Microservice across clusters (BookInfo) @praveingk (#314) 
     - [x] RBAC Example (how to add users and create new roles for them) @ArnavBalyan (#305)
